name: Main

on:
  push:
    branches:
      - ci_test
  pull_request:
    branches:
      - ci_test 

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build for linux
        uses: actions-rs/cargo@v1
        with:
          command: build 
          args: --release
      - name: Zip
        uses: vimtor/action-zip@v1
        with:
          files: |
            target/release/desktop-pet-rs
            target/release/assets.bin
            README.md
          dest: desktop-pet_linux_x86-64.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: desktop-pet_linux_x86-64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  